# Generated by Django 5.0.3 on 2025-07-08 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_complaint_body_alter_complaint_image_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for blog list', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content (HTML allowed)')),
                ('image_src', models.CharField(help_text="Path to blog cover image (e.g., 'blogimages/blog1.png')", max_length=255)),
                ('image_alt', models.CharField(help_text='Alt text for blog cover image', max_length=200)),
                ('meta_description', models.TextField(help_text='SEO meta description', max_length=300)),
                ('keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=500)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=200)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', max_length=300)),
                ('og_image', models.URLField(blank=True, help_text='Full URL to Open Graph image')),
                ('og_url', models.URLField(blank=True, help_text='Full URL to this blog post')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type', max_length=50)),
                ('og_site_name', models.CharField(default='Jephthah Adegbuyi', help_text='Open Graph site name', max_length=100)),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title', max_length=200)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description', max_length=300)),
                ('twitter_image', models.URLField(blank=True, help_text='Full URL to Twitter image')),
                ('twitter_site', models.CharField(default='@princejetro123', help_text='Twitter site handle', max_length=100)),
                ('twitter_creator', models.CharField(default='@princejetro123', help_text='Twitter creator handle', max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('read_time', models.CharField(help_text="Estimated read time (e.g., '7 min')", max_length=20)),
                ('tags', models.CharField(blank=True, help_text="Tags for the blog post (e.g., '#SmallBusiness #Marketing')", max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the post is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
